"""empty message

Revision ID: 51482a5d26e9
Revises: 7c22ab885410
Create Date: 2025-10-26 01:47:58.947588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51482a5d26e9'
down_revision: Union[str, Sequence[str], None] = '7c22ab885410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'color')
    # ### end Alembic commands ###
