# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2025-08-10T21:17:01+00:00

# from __future__ import annotations

from typing import List, Optional

from fastapi import FastAPI

from app.models import (
    Basket,
    BasketDish,
    BasketsBasketIdDishesDishIdPostRequest,
    Category,
    Dish,
    User,
)

app = FastAPI(
    title="Vaffel Bot API",
    version="0.0.1",
    servers=[{"url": "https://api.server.test/v1"}],
)


@app.get("/baskets/", response_model=List[Basket], tags=["Baskets"])
def get_baskets(user_id: str) -> List[Basket]:
    pass


@app.get(
    "/baskets/{basket_id}/dishes/", response_model=List[BasketDish], tags=["Baskets"]
)
def get_baskets_dishes(id: str) -> List[BasketDish]:
    pass


@app.post(
    "/baskets/{basket_id}/dishes/{dish_id}/",
    response_model=BasketDish,
    tags=["Baskets"],
)
def create_baskets_dishes(
    basket_id: str,
    dish_id: str = ...,
    body: BasketsBasketIdDishesDishIdPostRequest = None,
) -> BasketDish:
    pass


@app.delete(
    "/baskets/{basket_id}/dishes/{dish_id}/", response_model=None, tags=["Baskets"]
)
def delete_baskets_dishes(basket_id: str, dish_id: str = ...) -> None:
    pass


@app.get("/categories/", response_model=List[Category], tags=["Categories"])
def get_categories() -> List[Category]:
    pass


@app.get("/dishes/", response_model=List[Dish], tags=["Dishes"])
def get_dishes(
    category_id: Optional[str] = None, search: Optional[str] = None
) -> List[Dish]:
    pass


@app.post("/users/", response_model=User, tags=["Users"])
def create_user(body: User = None) -> User:
    pass


@app.get("/users/{id}/", response_model=User, tags=["Users"])
def get_user(id: str) -> User:
    pass
